notifications:
  email:
    - motakuk@gmail.com
language: python
install:
  - pip install pep8 --use-mirrors
python:
  - "3.3"
script:
  - cd P2PFileExchange
  - python3 -m unittest discover --start-directory=Tests --pattern=*.py